declare const mockModule: {
    setupPlayer: jest.Mock<any, any, any>;
    updateOptions: jest.Mock<any, any, any>;
    load: jest.Mock<any, any, any>;
    reset: jest.Mock<any, any, any>;
    play: jest.Mock<any, any, any>;
    pause: jest.Mock<any, any, any>;
    stop: jest.Mock<any, any, any>;
    setPlayWhenReady: jest.Mock<any, any, any>;
    getPlayWhenReady: jest.Mock<any, any, any>;
    seekTo: jest.Mock<any, any, any>;
    seekBy: jest.Mock<any, any, any>;
    setVolume: jest.Mock<any, any, any>;
    getVolume: jest.Mock<any, any, any>;
    setRate: jest.Mock<any, any, any>;
    getRate: jest.Mock<any, any, any>;
    getProgress: jest.Mock<any, any, any>;
    getPlaybackState: jest.Mock<any, any, any>;
    retry: jest.Mock<any, any, any>;
    add: jest.Mock<any, any, any>;
    move: jest.Mock<any, any, any>;
    remove: jest.Mock<any, any, any>;
    removeUpcomingTracks: jest.Mock<any, any, any>;
    skip: jest.Mock<any, any, any>;
    skipToNext: jest.Mock<any, any, any>;
    skipToPrevious: jest.Mock<any, any, any>;
    updateMetadataForTrack: jest.Mock<any, any, any>;
    updateNowPlayingMetadata: jest.Mock<any, any, any>;
    setQueue: jest.Mock<any, any, any>;
    getQueue: jest.Mock<any, any, any>;
    setRepeatMode: jest.Mock<any, any, any>;
    getRepeatMode: jest.Mock<any, any, any>;
    getTrack: jest.Mock<any, any, any>;
    getActiveTrackIndex: jest.Mock<any, any, any>;
    getActiveTrack: jest.Mock<any, any, any>;
    addListener: jest.Mock<any, any, any>;
    removeListeners: jest.Mock<any, any, any>;
    getConstants: jest.Mock<any, any, any>;
    acquireWakeLock: jest.Mock<any, any, any>;
    abandonWakeLock: jest.Mock<any, any, any>;
    validateOnStartCommandIntent: jest.Mock<any, any, any>;
};
export declare const Constants: any;
export default mockModule;
//# sourceMappingURL=NativeTrackPlayer.d.ts.map