import * as SplashScreen from 'expo-splash-screen';
import { useEffect, useRef } from 'react';
import { Animated, Easing, StyleSheet, View } from 'react-native';

const PRIMARY = '#1D9BF0';
const BAR_COLOR = '#FFFFFF';

/**
 * Proportional heights for the 9 waveform bars.
 * Bars are centred vertically to create a playful sound-wave shape.
 * These match the SVG logo generated by scripts/generate-assets.js.
 */
const BAR_HEIGHTS = [0.30, 0.55, 0.80, 0.50, 1.00, 0.45, 0.90, 0.60, 0.35];

/** Maximum height the tallest bar can reach (in dp). */
const LOGO_SIZE = 130;

/** Gap as a fraction of bar width – keeps things light and airy. */
const GAP_RATIO = 0.35;

const BAR_COUNT = BAR_HEIGHTS.length;

type Props = {
  onFinish: () => void;
};

export default function AnimatedSplashScreen({ onFinish }: Props) {
  const scale = useRef(new Animated.Value(1)).current;
  const opacity = useRef(new Animated.Value(1)).current;
  const nativeHidden = useRef(false);

  useEffect(() => {
    // Hide the native splash immediately – the animated splash is visually
    // identical (same blue bg + white bars) so the user sees no flash.
    if (!nativeHidden.current) {
      nativeHidden.current = true;
      SplashScreen.hideAsync();
    }

    // --- Animation timeline ---
    const pulse = (toValue: number) =>
      Animated.spring(scale, {
        toValue,
        useNativeDriver: true,
        friction: 6,
        tension: 120,
      });

    const pulse1 = Animated.sequence([pulse(1.15), pulse(1)]);
    const pulse2 = Animated.sequence([pulse(1.15), pulse(1)]);

    const hold = Animated.delay(300);

    const fadeOut = Animated.timing(opacity, {
      toValue: 0,
      duration: 500,
      easing: Easing.out(Easing.ease),
      useNativeDriver: true,
    });

    Animated.sequence([pulse1, pulse2, hold, fadeOut]).start(({ finished }) => {
      if (finished) {
        onFinish();
      }
    });
  }, [onFinish, scale, opacity]);

  // --- Bar geometry (matches the SVG generator proportions) ---
  const barWidth = LOGO_SIZE / (BAR_COUNT + (BAR_COUNT - 1) * GAP_RATIO);
  const gap = barWidth * GAP_RATIO;
  const pillRadius = barWidth / 2; // fully rounded pill

  return (
    <View style={styles.container}>
      <Animated.View
        style={[
          styles.logoWrap,
          { opacity, transform: [{ scale }] },
        ]}
      >
        {BAR_HEIGHTS.map((h, i) => (
          <View
            key={i}
            style={[
              styles.bar,
              {
                width: barWidth,
                height: LOGO_SIZE * h,
                borderRadius: pillRadius,
                marginLeft: i === 0 ? 0 : gap,
              },
            ]}
          />
        ))}
      </Animated.View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoWrap: {
    flexDirection: 'row',
    alignItems: 'center',      // centre bars vertically → sound-wave look
    justifyContent: 'center',
  },
  bar: {
    backgroundColor: BAR_COLOR,
  },
});
